version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=amyuqiliang@gmail.com
  frontend:
    image: ghcr.io/uoft-utsc-cs-sandbox/frontend-av
    container_name: frontend
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=audiovisualizer.live
      - LETSENCRYPT_HOST=audiovisualizer.live
  backend:
    image: ghcr.io/uoft-utsc-cs-sandbox/backend-av
    container_name: backend
    restart: always
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=api.audiovisualizer.live
      - LETSENCRYPT_HOST=api.audiovisualizer.live
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PASSWORD=admin
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_DB_HOST=postgres
      - POSTGRES_DB_PORT=5432
      - SESSION_SECRET=somethingsecret
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
